#!/bin/bash
#clone vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
# run plugin install
vim +PluginInstall +qall

#clone tmux plugin manager
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
#instal powerline fonts patched
wget https://github.com/Lokaltog/powerline/raw/develop/font/PowerlineSymbols.otf https://github.com/Lokaltog/powerline/raw/develop/font/10-powerline-symbols.conf
mkdir -p ~/.fonts/ && mv PowerlineSymbols.otf ~/.fonts/
fc-cache -vf ~/.fonts
mkdir -p ~/.config/fontconfig/conf.d/ && mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
# set up link to dotfiles
cd ~
declare -a arr=(".vimrc" ".tmux.conf" ".bashrc")
for i in "${arr[@]}"
do
	FILE=$i
	   echo "Creating link for $FILE"
      
if test -f "$FILE";
then echo "$FILE exist creating backup"
	if test -f "$FILE.back";then
		echo "Backup file alredy exist doing noting"
	else
		mv $FILE $FILE.back
		ln -s dotfiles/$FILE $FILE
	
	fi
	
else
	ln -s dotfiles/$FILE $FILE
fi
done
